// examples/electron-vue/src/components/Editors.vue
<script>
import { Grammarly, GrammarlyEditorPlugin } from "@grammarly/editor-sdk-vue";
import { demoText, demoClientId } from "./demo";

export default {
  data: () => ({ text: demoText, clientId: demoClientId }),
  components: { Grammarly, GrammarlyEditorPlugin },
};
</script>

<template>
  <Grammarly :clientId="clientId" :config="{ oauth: { redirectUri: 'example://grammarly-auth/' } }">
    <div>
      <h2>Textarea</h2>
      <GrammarlyEditorPlugin>
        <textarea v-model="text.textarea" rows="10"></textarea>
      </GrammarlyEditorPlugin>

      <h2>Input</h2>
      <label htmlFor="test-input">Label</label>
      <GrammarlyEditorPlugin>
        <input v-model="text.input" id="test-input" />
      </GrammarlyEditorPlugin>

      <h2>Contenteditable</h2>
      <GrammarlyEditorPlugin>
        <div contentEditable="true" v-html="text.contenteditable"></div>
      </GrammarlyEditorPlugin>
    </div>
  </Grammarly>
</template>

// examples/electron-react/src/Editors.js
import React from "react";

import { Grammarly, GrammarlyEditorPlugin } from "@grammarly/editor-sdk-react";
import { demoClientId, demoText } from "./demo";
import "./style.css";

export const Editors = () => {
  return (
    <Grammarly clientId={demoClientId} config={{
      oauth: { redirectUri: "example://grammarly-auth/" },
    }}>
      <h2>Textarea</h2>
      <GrammarlyEditorPlugin>
        <textarea defaultValue={demoText.textarea} rows={10}></textarea>
      </GrammarlyEditorPlugin>

      <h2>Input</h2>
      <label htmlFor="test-input">Label</label>
      <GrammarlyEditorPlugin>
        <input defaultValue={demoText.input} id="test-input" />
      </GrammarlyEditorPlugin>

      <h2>Contenteditable</h2>
      <GrammarlyEditorPlugin>
        <div
          contentEditable="true"
          dangerouslySetInnerHTML={{
            __html: demoText.contenteditable,
          }}
        ></div>
      </GrammarlyEditorPlugin>
    </Grammarly>
  );
};
